; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -mtriple=amdgcn-amd-amdhsa -passes='cgscc(amdgpu-simple-attributor)' -S  < %s 2>&1 | FileCheck %s

;
; Test to verify AAUniformWorkGroupSize propagation behavior in CGSCC context.
;
; This test demonstrates top-down propagation from kernel to device function.
; The kernel has uniform-work-group-size="true", and we expect this to propagate
; to the device function it calls.
;
; Expected behavior: @device_func should inherit uniform-work-group-size="true"
; from @kernel because we add ALL module functions to Attributor's scope.

; CHECK: [AMDGPUSimpleAttributor] Processing SCC
; CHECK: [AMDGPUSimpleAttributor] Added {{[0-9]+}} functions from module to Attributor

define amdgpu_kernel void @kernel() #0 {
; CHECK-LABEL: define amdgpu_kernel void @kernel(
; CHECK-SAME: ) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @device_func()
; CHECK-NEXT:    call void @device_func_v2()
; CHECK-NEXT:    ret void
;
entry:
  call void @device_func()
  call void @device_func_v2()
  ret void
}

; The device function should get uniform-work-group-size="true" propagated from kernel
define internal void @device_func() {
; CHECK-LABEL: define internal void @device_func(
; CHECK-SAME: ) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @nested_device_func()
; CHECK-NEXT:    ret void
;
entry:
  call void @nested_device_func();
  ret void
}

; Another device function called by device_func - should also get the attribute
define internal void @nested_device_func() {
; CHECK-LABEL: define internal void @nested_device_func(
; CHECK-SAME: ) #[[ATTR1:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @deeper_nested_device_func()
; CHECK-NEXT:    ret void
;
entry:
  call void @deeper_nested_device_func();
  ret void
}

define internal void @deeper_nested_device_func() {
; CHECK-LABEL: define internal void @deeper_nested_device_func(
; CHECK-SAME: ) #[[ATTR1]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    ret void
;
entry:
  ret void
}

; Modify device_func to call nested_device_func
define internal void @device_func_v2() {
; CHECK-LABEL: define internal void @device_func_v2(
; CHECK-SAME: ) #[[ATTR1]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @nested_device_func()
; CHECK-NEXT:    ret void
;
entry:
  call void @nested_device_func()
  ret void
}

define amdgpu_kernel void @kernel_false() #1 {
; CHECK-LABEL: define amdgpu_kernel void @kernel_false(
; CHECK-SAME: ) #[[ATTR1]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @device_func_v2()
; CHECK-NEXT:    ret void
;
entry:
  call void @device_func_v2()
  ret void
}

attributes #0 = { "uniform-work-group-size"="true" }
attributes #1 = { "uniform-work-group-size"="false" }
